basePath: /v1
definitions:
  user.User:
    properties:
      createAt:
        type: integer
      enable:
        type: boolean
      id:
        description: '@gotags: validate:"required"'
        type: integer
      mobile:
        description: '@gotags: validate:"gte=10000000000,lte=100000000000"'
        maximum: 100000000000
        minimum: 10000000000
        type: integer
      name:
        description: '@gotags: validate:"required"'
        type: string
      updateAt:
        type: integer
    required:
    - id
    - name
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API文档.
  title: API DOC
  version: "1.0"
paths:
  /v1/user:
    get:
      consumes:
      - application/json
      description: 根据用户ID获取用户信息
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            $ref: '#/definitions/user.User'
      summary: 获取用户信息
swagger: "2.0"
