root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "cp main ./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "logs"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./tmp/main --env=pro"
  include_dir = []
  include_ext = ["ini", "toml", "html", "Dockerfile"]
  kill_delay = "0s"
  log = "./logs/air.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
