// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

// Injectors from service.go:

func InitService() (Service, error) {
	userDao := newDao()
	userService := newService(userDao)
	return userService, nil
}

// service.go:

type Service struct {
	dao dao
}

func newService(dao2 dao) Service {
	return Service{dao: dao2}
}

func (s *Service) get() {

}

func (s *Service) getList() {

}

func (s *Service) post() {

}

func (s *Service) put() {

}

func (s *Service) delete() {

}
