// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

// Injectors from wire.go:

func initService() Service {
	userDao := newDao()
	userCache := newCache()
	service2 := newService(userDao, userCache)
	return service2
}
