// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

// Injectors from wire.go:

func initController() *controller {
	userDao := newDao()
	userCache := newCache()
	userService := newService(userDao, userCache)
	userController := newController(userService)
	return userController
}
